- name: functions
  hosts: local
  connection: local
  vars:
    data:
       env: DevOps
       app: nginx   
    
    technologies: DevOps, linux, shell, ansible
    user_name: "jaswanth"
    gmail: JRF@GMAIL.COM
    ipaddress: "1900.22.32.11"
    #list
    listtags:
    - key: app
      value: payment
    - key: env
      value: dev  
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello, {{ name | default ( 'Ramesh' ) }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "Technologies are: {{ technologies | split(',') }}"

  - name: convert dictionary to list
    ansible.builtin.debug:
      msg: "data is : {{ data | dict2items }}"

  - name: convert list into map or dictionary
    ansible.builtin.debug:
      msg: "tag map: {{ listtags | items2dict }}"

  - name: read yaml and take into variable
    ansible.builtin.set_fact:
     student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

  - name: convert yaml to json
    ansible.builtin.debug:
     msg: "json: {{ student_yaml | to_json }}"

  - name: save json to file
    ansible.builtin.copy:
     dest: ./std-data.json
     content: "{{ student_yaml | to_nice_json }}"

  - name: convert uppercase
    ansible.builtin.debug:
      msg: "{{ user_name | upper }}"

  - name: convert lowercase
    ansible.builtin.debug:
      msg: "{{ gmail | lower }}"

  - name: check IP is valid or not
    ansible.builtin.debug: 
      msg: "{{ ipaddress | ansible.utils.ipv4 }}"
    