- name: install multiple packages
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: 
     ansible.builtin.package:
      msg: "Hello {{ item }}" # item is reserved for loops
      state: latest
     loop:
       - nginx
       - mongodb
       - mysql
       - ubuntu
       - ansible

