- name: install multiple packages
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: print names 
     ansible.builtin.package:
      name: "{{ item }}" # item is reserved for loops
      state: latest
     loop:
       - nginx
       - mongodb
       - mysql
       - ansible

