- name: play level variables
  hosts: localhost
  connection: local #ansible is connecting to localhost
  vars:
    COURSE: Devops with AWS
    DURATION: 10HRS
    TRAINER: JR
  tasks:
  - name: print the course info
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "course name: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"